services:
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tire_reader:
    build:
      context: ./tire_vision
      dockerfile: Dockerfile
    container_name: kolobok_tire_reader
    environment:
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
